### ISSUE TITLE
cfg-if is awkward to use with 2018 edition

### ISSUE THREAD

**Issue by d3zd3z** [alexcrichton/cfg-if#17]
In order to use cfg-if with Rust 2018 style 'use' for macros, it is necessary to also import `__cfg_if_apply`, and `__cfg_if_items`. Perhaps these can be referenced via $crate so that the cfg_if macro will work even as the only macro imported.

**Comment by alexcrichton** [comment]
Just to confirm, but are you using the most recent version of cfg-if? The master branch is supposed to solve these issues

**Comment by mitchtbaum** [comment]
> The master branch is supposed to solve these issues

this was a little bit confusing, but after a second review, afaict, there aren't any newer changes yet to be released, and "0.1.6 is in theory compatible with the 2018 edition macro import story".

seems like this crate is definitely work looking into further
