### ISSUE TITLE
new release planned?

### ISSUE THREAD

**Issue by mitchtbaum** [alexcrichton/cfg-if#19]
would fix #17

**Comment by alexcrichton** [comment]
Hm can you confirm that the 0.1.6 version on crates.io doesn't work? It is in theory compatible with the 2018 edition macro import story

**Comment by mitchtbaum** [comment]
I haven't tried it yet; just sorting through open issues now.  Hoping to read others' feedback first.  Looks like https://crates.io/crates/cfg-if/reverse_dependencies actually answers my concerns thoroughly.
