### ISSUE TITLE
variant macro for blocks

### ISSUE THREAD

**Issue by Lokathor** [alexcrichton/cfg-if#26]
I often want to cfg some code, but I want to do it on blocks inside a function instead of at the item level.

Would you be open to adding a second macro such as `cfg_if_block` (or other name) that does all the same stuff but working on `:block` instead of `:item`? I can do the PR if you're interested in the idea.

**Comment by gnzlbg** [comment]
Possibly dup of #8 .

**Comment by Lokathor** [comment]
I already have a PR waiting for the docs related issues.

**Comment by Lokathor** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f26008f95e5aebf5e8276fa804940a51

demo attempt

**Comment by alexcrichton** [comment]
Given @ogoffart's [implementation](https://github.com/alexcrichton/cfg-if/issues/25#issuecomment-533629389) I think it would be easy enough to switch to `:tt` lists and use the same macro for supporting items/expressions/etc, probably even methods!

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/cfg-if/pull/28 I believe
