### ISSUE TITLE
Document Supported Versions

### ISSUE THREAD

**Issue by Alexhuszagh** [alexcrichton/cfg-if#29]
It would be nice if `cfg-if` documented the versions of Rustc it currently supports, using a badge similar to:
[![Rustc Version 1.24+](https://img.shields.io/badge/rustc-1.24+-lightgray.svg)](https://blog.rust-lang.org/2018/02/15/Rust-1.24.html)
[![Rustc Version 1.31+](https://img.shields.io/badge/rustc-1.31+-lightgray.svg)](https://blog.rust-lang.org/2018/12/06/Rust-1.31-and-rust-2018.html)

Version 0.1.10 recently broke compatibility with for versions <= 1.31.0, with the following errors:
- feature `rename-dependency` is required
- Produces the warning: `non-ident macro paths are experimental (see issue #35896)`.

I'm fine with breaking backwards compatibility for deprecated compiler versions (especially ones with vulnerabilities, like <= 1.25.0), but it would be nice to document what Rustc versions are, in-fact, supported. I believe the current supported version is 1.31.0.

**Comment by cardoe** [comment]
Similarly this is causing log to not build with the version of Rust it says it supports. https://github.com/rust-lang-nursery/log/issues/358

**Comment by cardoe** [comment]
Created #30 as its own issue for my specific case but I support this overall.

**Comment by alexcrichton** [comment]
Thanks for the report, but I personally do not have the time to actively invest in this documentation for all the crates that I maintain. I don't mind merging PRs but I will also remove the documentation/CI if it becomes burdensome.
