### ISSUE TITLE
newer features break older Rust support and by extension log crate's API

### ISSUE THREAD

**Issue by cardoe** [alexcrichton/cfg-if#30]
https://github.com/alexcrichton/cfg-if/commit/75e817fa2cdd9d3cb2c558fa91ba3dacdbfa8d73 appears to have broken the support for older Rust version such as 1.16.0 which the https://github.com/rust-lang-nursery/log crate says it will always support.

**Comment by cardoe** [comment]
Due to this issue, this has broken log as noted here https://github.com/rust-lang-nursery/log/issues/358

**Comment by alexcrichton** [comment]
Thanks for the report, but I do not support Rust 1.16.0 with this crate, so I'm going to close this.
