### ISSUE TITLE
What's stopping 1.0?

### ISSUE THREAD

**Issue by Lokathor** [alexcrichton/cfg-if#31]
What problems does the crate have that are blockers for issuing a 1.0.0 version?

**Comment by alexcrichton** [comment]
Nothing that I know of, I have largely just not had the desire to upset the ecosystem using this crate and make everyone think they need to upgrade. It doesn't seem worth the effort when there are parallel efforts to include this in libstd.

**Comment by Lokathor** [comment]
Ah, I was not aware of efforts to include this in libstd.

**Comment by Xanewok** [comment]
See https://github.com/rust-lang/rust/issues/57446, which I believe is related.

**Comment by Lokathor** [comment]
Interesting! Subscribed to that. In the meantime I just put a similar macro in one of my 1.x crates.

**Comment by Veetaha** [comment]
So does it mean this crate is never going to be `1.0`? From my viewpoint, it's better to transition to `1.0` earlier than never. It won't be hard because this should be backward-compatible. The more we wait the more crates use `0.1.10` version...

**Comment by Lokathor** [comment]
Honestly the 1.0 doesn't even have to semver trick back onto the 0.1.10 version to begin with. This is a compile time macro, compat between crates isn't an issue because people don't (generally) export this from a crate for other crates to use.

The main reason for 1.0 is to take a firm stance that the crate is production ready and intended to stay that way for quite a while.

**Comment by alexcrichton** [comment]
I don't have anything to add over [what I mentioned previously](https://github.com/alexcrichton/cfg-if/issues/31#issuecomment-556045495). That will always be true though and is largely just something to acknowledge rather than deter a 1.0 release. I think it would probably be fine at this point to just bump the crate to 1.0.

**Comment by Lokathor** [comment]
@alexcrichton do you have a link to any sort of tracking issue to get cfg-if into the standard library?

**Comment by alexcrichton** [comment]
https://github.com/rust-lang/rust/pull/59443, mentioned [previously](https://github.com/alexcrichton/cfg-if/issues/31#issuecomment-607389622), is the only discussion that I'm aware of

**Comment by alexcrichton** [comment]
I've gone ahead and bumped this to 1.0
