### ISSUE TITLE
#[allow(clippy::assertions_on_constants)] does not work on older versions of Rust

### ISSUE THREAD

**Issue by soc** [alexcrichton/cfg-if#34]
This change: https://github.com/alexcrichton/cfg-if/commit/75e817fa2cdd9d3cb2c558fa91ba3dacdbfa8d73

Broke the build of the `[directories](https://github.com/soc/directories-rs)` (and `dirs`) crates:
https://travis-ci.org/soc/directories-rs/jobs/592813734

Could this code be replaced by a normal import of `clippy`, such that it keeps working on existing Rust versions?

**Comment by alexcrichton** [comment]
Thanks for the report but this is a change in a test and this crate doesn't work to support 4-year-old verisons of Rust right now.
