### ISSUE TITLE
cargo build failed permission denied

### ISSUE THREAD

**Issue by gotope** [alexcrichton/cfg-if#40]
windows 7 x64, cargo build failed permission denied

active toolchain
nightly-x86_64-pc-windows-msvc (default)
rustc 1.51.0-nightly (04caa632d 2021-01-30)

/e/gitlocal/cfg-if (main)
$ cargo build --verbose
   Compiling cfg-if v1.0.0 (E:\gitlocal\cfg-if)
     Running `rustc --crate-name cfg_if --edition=2018 'src\lib.rs' --error-format=json 
	 --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no 
	 -C debuginfo=2 -C metadata=c2a97ad137455fb4 -C extra-filename=-c2a97ad137455fb4 
	 --out-dir 'E:\gitlocal\cfg-if\target\debug\deps' 
	 -C 'incremental=E:\gitlocal\cfg-if\target\debug\incremental' 
	 -L 'dependency=E:\gitlocal\cfg-if\target\debug\deps'`
error: failed to build archive: permission denied

error: aborting due to previous error

error: could not compile `cfg-if`

Caused by:
  process didn't exit successfully: `rustc --crate-name cfg_if --edition=2018 'src\lib.rs' 
  --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link 
  -C embed-bitcode=no -C debuginfo=2 -C metadata=c2a97ad137455fb4 -C extra-filename=-c2a97ad137455fb4 
  --out-dir 'E:\gitlocal\cfg-if\target\debug\deps' 
  -C 'incremental=E:\gitlocal\cfg-if\target\debug\incremental' 
  -L 'dependency=E:\gitlocal\cfg-if\target\debug\deps'` (exit code: 1)

**Comment by alexcrichton** [comment]
Thanks for the report, but this looks like a local issue with rustc that's not specific to this crate. If you're unable to figure out the issue I'd recommend reporting to rust-lang/rust.
