### ISSUE TITLE
A crate to parametrize compile-time conditionals?

### ISSUE THREAD

**Issue by Wandalen** [alexcrichton/cfg-if#54]
Is that something possible?

https://users.rust-lang.org/t/a-crate-to-parametrize-compile-time-conditionals/75027/3

**Comment by alexcrichton** [comment]
Unfortunately no, this crate can't be used for that. AFAIK build scripts are mainly used for that.

**Comment by Wandalen** [comment]
@alexcrichton Build script? Any example? 

Is that possible?

**Comment by Wandalen** [comment]
Apparently author is too busy to answer all questions. 
For those who are interested in such kind of crate, it is [here](https://github.com/katharostech/cfg_aliases). Useful thing!
